#include "fw.webex.object.context.th"

namespace FWWebEx
using namespace FWWebEx
using namespace FWWebEx.Tools

procedure u_SwitchTst()
    if (Empty(ProcName(1)))
        private cAcesso:=""//Prevent Error on EEcView=>EnchoiceBar
        FWExampleTools():Execute({||SwitchTst()},ProcName(),.F.)
    else
        SwitchTst()
    endif
return

static procedure SwitchTst()

    local cProcName:=ProcName() as character

    local jSwitch as json

    local oSwitch as object

    jSwitch:={;
         "A":{|cOption as character,i as numeric,cProcName as character|MsgInfo("&Eacute; "+cOption+"["+tlpp.ToStr(i)+"]",cProcName)};
        ,"B":{|cOption as character,i as numeric,cProcName as character|MsgInfo("&Eacute; "+cOption+"["+tlpp.ToStr(i)+"]",cProcName)};
    }
    oSwitch:=Switch():New("")
    oSwitch:SetDefault({|cProcName as character|MsgInfo("Desconhecido",cProcName)})

    ForEach():Evaluate(jSwitch,{|k as character,b as codeblock|;
         oSwitch:AddCase(k,b);
    },.T.)

    ForEach():Evaluate(jSwitch,{|k as character,b as codeblock,i as numeric|;
          oSwitch:Set(k):Eval(k,i,cProcName);
    },.T.)

    oSwitch:Set():Eval(cProcName)

    FreeObj(@jSwitch)
    FreeObj(@oSwitch)

return
