#include "fw-tlpp-core.th"

//Considerando que callProcRestCrudTLPP depende de DNA.TECH.USERRESTCRUDTLPP
//u_callProcRestCrudTLPPEx008 atuara como um mock da callProcRestCrudTLPP.
@POST(endpoint="/u_callProcRestCrudTLPPEx008/post/",description="u_callProcRestCrudTLPPEx008")
function u_callProcRestCrudTLPPEx008()

    local cJSON as character

    local jHeader as json

    beginContent var cJSON
{
    "method": "get",
    "path": "/userRestCrudADVPL/codAlias/",
    "PageNumber": 1,
    "RowspPage": 10,
    "table": {
        "alias": "SRA",
        "name": "SRA990",
        "description": "Funcionarios",
        "index": "RA_FILIAL+RA_MAT",
        "items": [
            {
                "detail": {
                    "row": 1,
                    "key": "01000004",
                    "recNo": 4,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000004",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "ANDREI",
                        "RA_CC": "10206001",
                        "RA_DEPIR": "02",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 6433.57,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 2,
                    "key": "01000007",
                    "recNo": 7,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000007",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "CLAUDINEI",
                        "RA_CC": "10203001",
                        "RA_DEPIR": "03",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 3045.6,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 3,
                    "key": "01000008",
                    "recNo": 8,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000008",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "FABIO",
                        "RA_CC": "10303017",
                        "RA_DEPIR": "01",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 8216,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 4,
                    "key": "01000010",
                    "recNo": 10,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000010",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "LEONARDO",
                        "RA_CC": "10303017",
                        "RA_DEPIR": "01",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 12498.29,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 5,
                    "key": "01000012",
                    "recNo": 12,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000012",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "EDVALDO ALVES",
                        "RA_CC": "10304033",
                        "RA_DEPIR": "00",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 2998.82,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 6,
                    "key": "01000013",
                    "recNo": 13,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000013",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "MARCOS",
                        "RA_CC": "10201008",
                        "RA_DEPIR": "03",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 10560.44,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 7,
                    "key": "01000014",
                    "recNo": 14,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000014",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "WERICLES ARAUJO",
                        "RA_CC": "10304033",
                        "RA_DEPIR": "02",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 2998.82,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 8,
                    "key": "01000015",
                    "recNo": 15,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000015",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "CARLOS EDUARDO",
                        "RA_CC": "10206001",
                        "RA_DEPIR": "00",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 6047.78,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 9,
                    "key": "01000016",
                    "recNo": 16,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000016",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "FELIPE CHAVES",
                        "RA_CC": "10304032",
                        "RA_DEPIR": "00",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 2370.4,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            },
            {
                "detail": {
                    "row": 10,
                    "key": "01000018",
                    "recNo": 18,
                    "items": {
                        "RA_FILIAL": "01",
                        "RA_MAT": "000018",
                        "RA_SEXO": "M",
                        "RA_APELIDO": "WAGNER CERQUEIR",
                        "RA_CC": "10304032",
                        "RA_DEPIR": "01",
                        "RA_CATFUNC": "M",
                        "RA_SALARIO": 2370.4,
                        "RA_ADTPOSE": "***N**"
                    }
                }
            }
        ]
    },
    "hasNextPage": false,
    "TotalRows": 10,
    "TotalPages": 1
}
    endContent

    if (Type("oRest")=="O")
        jHeader:=JSONObject():New()
        jHeader["Content-Type"]:="application/json; charset=utf-8"
        jHeader["Cache-Control"]:="no-cache"
        jHeader["Content-Length"]:=tlpp.ToStr(Len(cJSON))
        oRest:SetHeaderResponse(jHeader)
        oRest:SetResponse(cJSON)
    endif

    FreeObj(@jHeader)

return(.T.)
