/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

namespace FWWebEx

#include "fw.webex.th"

class WebExButton from WebExControl

    protected data cButtonLabel as character
    protected data cButtonType as character

    protected data oButton as object
    protected data oButtonIcon as object

    public method New(cButtonLabel as character,cButtonType as character) as object

    public method SetButtonLabel(cButtonLabel as character) as character
    public method SetButtonType(cButtonType as character) as character

    public method SetButtonIcon(cIconName as character,cIconType as character,lIconBefore as logical) as object

endclass

method New(cButtonLabel,cButtonType) class WebExButton
    paramtype 1 var cButtonLabel as character optional default ""
    paramtype 2 var cButtonType as character optional default "submit"
    ::cButtonLabel:=cButtonLabel
    ::cButtonType:=Lower(cButtonType)
    _Super:New("button")
    ::oButton:=self
    ::AddClass("btn")
    ::AddClass("btn-primary")
    ::SetButtonLabel()
    ::SetButtonType()
return(self)

method SetButtonLabel(cButtonLabel) class WebExButton
    paramtype 1 var cButtonLabel as character optional default ::cButtonLabel
    ::SetMemberData("cButtonLabel",cButtonLabel)
    ::SetContent(::cButtonLabel)
return(self)

method SetButtonType(cButtonType) class WebExButton
    paramtype 1 var cButtonType as character optional default ::cButtonType
    ::SetMemberData("cButtonType",Lower(cButtonType))
    ::SetAttr("type",cButtonType)
return(self)

method SetButtonIcon(cIconName,cIconType,lIconBefore) class WebExButton
    paramtype 1 var cIconName as character optional default "bootstrap"
    paramtype 2 var cIconType as character
    paramtype 3 var lIconBefore as logical optional default .T.
    WITH WEBEXOBJECT ::oButton
        WITH WEBEXOBJECT ::oButtonIcon CLASS WebExIcon ARGS cIconName,cIconType,lIconBefore
        END WEBEXOBJECT
    END WEBEXOBJECT NOADDCHILD
return(self)
