/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

namespace FWWebEx

#include "fw.webex.th"

class WebExDataTableFilter from WebExDiv

    protected data cTargetTableID as character
    protected data jTargetTableFields as json

    protected data oContainer as object
    protected data oContainerGroup as object
    protected data oContainerGroupField as object
    protected data oContainerGroupValue as object
    protected data oContainerGroupButton as object

    public method New(cTargetTableID as character,jTargetTableFields as json) as object

endclass

method New(cTargetTableID,jTargetTableFields) class WebExDataTableFilter

    local cScript as character
    local cIDField as character
    local cIDValue as character
    local cIDButton as character
    local cIDContainer as character

    local cInputName:="FWWebExDataTableFilterValue"
    local cInputType:="search"
    local cInputPlaceHolder:="Filter..."
    local cInputTitle:="FWWebExDataTableFilter"

    paramtype 1 var cTargetTableID as character
    paramtype 2 var jTargetTableFields as json

    ::cTargetTableID:=cTargetTableID
    ::jTargetTableFields:=jTargetTableFields

    _Super:New()

    ::oContainer:=self

    WITH WEBEXOBJECT ::oContainer
        cIDContainer:=.:GetID()
        .:AddClass("datatable-filter-wrapper mb-2")
        .:SetFixedID("FWWebExDataTableFilter_"+cIDContainer)
        WITH WEBEXOBJECT ::oContainerGroup CLASS WebExInputGroup
            .:AddClass("input-group-sm")
            WITH WEBEXOBJECT ::oContainerGroupField CLASS WebExControl type select
                cIDField:=.:GetID()
                .:AddClass("form-select form-select-sm")
                .:SetFixedID("FWWebExDataTableFilterField_"+cIDField)
            END WEBEXOBJECT
            WITH WEBEXOBJECT ::oContainerGroupValue CLASS WebExInput ARGS cInputName,cInputType,cInputPlaceHolder,cInputTitle
                cIDValue:=.:GetID()
                .:SetAttr("aria-label","Filter")
                .:SetFixedID("FWWebExDataTableFilterValue_"+cIDValue)
            END WEBEXOBJECT
            WITH WEBEXOBJECT ::oContainerGroupButton CLASS WebExButton ARGS "Filter","button"
                cIDButton:=.:GetID()
                .:AddClass("btn btn-primary")
                .:SetFixedID("FWWebExDataTableFilterButton_"+cIDButton)
                .:SetButtonIcon("fa-filter","fontawesome",.F.)
            END WEBEXOBJECT
            beginContent var cScript
                (function(){

                    const input = document.getElementById("FWWebExDataTableFilterValue___ID_VALUE__");

                    if (!input) {
                        return;
                    }

                    let FWWebExFilterTimer___ID_VALUE__;

                    function FWWebExFilterBuildSelectField___ID_CONTAINER__() {
                        const fields = __BUILD__SELECT_FIELDS__;
                        const select = document.getElementById("FWWebExDataTableFilterField___ID_FIELD__");
                        fields.fields.forEach(field => {
                            const opt = document.createElement("option");
                            opt.value = field.name.trim();
                            opt.textContent = field.label.trim();
                            select.appendChild(opt);
                        });
                    }

                    document.getElementById("FWWebExDataTableFilterButton___ID_BUTTON__").addEventListener("click", function () {
                        // garante que jQuery + DataTable estao carregados
                        if (FWWebExHasDataTables()) {
                            let table = $("#__ID_TARGET_TABLE__").DataTable();
                            let FWWebExFilterFiled = document.getElementById("FWWebExDataTableFilterField___ID_FIELD__").value;
                            let FWWEbExFilterValue = document.getElementById("FWWebExDataTableFilterValue___ID_VALUE__").value.trim();
                            table.settings()[0].oInit.FWWebExFilter = (FWWebExFilterFiled && FWWEbExFilterValue) ? { [FWWebExFilterFiled]: FWWEbExFilterValue } : {};
                            table.ajax.reload(); // recarrega o DataTable usando o novo filtro
                        }
                    });

                    FWWebExFilterBuildSelectField___ID_CONTAINER__();

                    // Use 'input' event for better handling of changes (e.g., paste, clear)
                    input.addEventListener("input", function(e) {

                        clearTimeout(FWWebExFilterTimer___ID_VALUE__);

                        FWWebExFilterTimer___ID_VALUE__ = setTimeout(() => {

                            let term = this.value.trim().toLowerCase();

                            // garante que jQuery + DataTable estao carregados
                            if (FWWebExHasDataTables()) {
                                if ($.fn.DataTable.isDataTable("#__ID_TARGET_TABLE__")) {
                                    let table = $("#__ID_TARGET_TABLE__").DataTable();
                                    let tableInfo = table.page.info();
                                    // Disable ServerSide if FWWebExPanelFilterEx
                                    const hasExtendedFilter = FWWebExHasDataTableFilters(table, ['FWWebExPanelFilterEx']);
                                    let isServerSide = !hasExtendedFilter?.FWWebExPanelFilterEx && table.settings()[0].oFeatures.bServerSide;
                                    // Reset search settings when term is empty
                                    if (!term) {
                                        table.settings()[0].oInit.FWWebExFilter = {}; // Clear custom filter
                                        if (isServerSide) {
                                            table.search('').columns().search('').page(0).draw(); // Reset global and column searches, go to first page
                                            table.ajax.reload(); // Reload from server
                                        } else {
                                            table.search('').columns().search('').page(0).draw(); // Client-side reset
                                        }
                                        return;
                                    }
                                    // Handle server-side search
                                    if (isServerSide) {
                                        let FWWebExFilterFiled = document.getElementById("FWWebExDataTableFilterField___ID_FIELD__").value;
                                        let FWWEbExFilterValue = document.getElementById("FWWebExDataTableFilterValue___ID_VALUE__").value.trim();
                                        table.settings()[0].oInit.FWWebExFilter = (FWWebExFilterFiled && FWWEbExFilterValue) ? { [FWWebExFilterFiled]: FWWEbExFilterValue } : {};
                                        table.ajax.reload();
                                    } else {
                                        // Client-side search
                                        // Get selected column field and search value
                                        const FWWebExFilterFiled = document.getElementById("FWWebExDataTableFilterField___ID_FIELD__").value;
                                        const FWWEbExFilterValue = document.getElementById("FWWebExDataTableFilterValue___ID_VALUE__").value.trim();
                                        // Find the column index in the table by matching data-field of <th>
                                        const thElements = table.columns().header().toArray(); // array of <th>
                                        const columnIndex = thElements.findIndex(th => th.dataset.field === FWWebExFilterFiled);

                                        // Split the search value by ";" into multiple tokens
                                        const terms = FWWEbExFilterValue
                                            .split(";")
                                            .map(t => t.trim().toLowerCase())
                                            .filter(t => t.length > 0); // remove empty entries

                                        table.rows().every(function () {
                                            const rowData = this.data();

                                            // If no column selected or no search term, keep the row visible
                                            if (!columnIndex  || terms.length === 0) {
                                                $(this.node()).show();
                                                return;
                                            }

                                            // / Get value of the selected column by index
                                            const columnValue = String(rowData[columnIndex] ?? "").toLowerCase();

                                            // Match if the column contains ANY of the terms
                                            const match = terms.some(t => columnValue.includes(t));

                                            // Show or hide the row locally based on the match result
                                            $(this.node()).toggle(match);
                                        });
                                    }
                                } else {
                                    console.warn("Target table #__ID_TARGET_TABLE__ not found to apply search.");
                                }
                            } else {
                                console.error("DataTables plugin is not available. Please check if the JS file has been imported.");
                            }

                        }, 300); // Debounce 300ms

                    });

                })();
            endContent
            cScript:=WebExHelper():StrReplaceEx(;
                cScript;
                ,{"__ID_FIELD__",cIDField};
                ,{"__ID_VALUE__",cIDValue};
                ,{"__ID_BUTTON__",cIDButton};
                ,{"__ID_CONTAINER__",cIDContainer};
                ,{"__ID_TARGET_TABLE__",::cTargetTableID};
                ,{"__BUILD__SELECT_FIELDS__",::jTargetTableFields:ToJSON()};
            )
            WITH WEBEXOBJECT CLASS WebExScript
                .:SetContent(cScript)
            END WEBEXOBJECT
        END WEBEXOBJECT
    END WEBEXOBJECT NOADDCHILD

return(self)
