/*
  __                                  _
 / _|  ___   _ __   ___   __ _   ___ | |__
| |_  / _ \ | '__| / _ \ / _` | / __|| '_ \
|  _|| (_) || |   |  __/| (_| || (__ | | | |
|_|   \___/ |_|    \___| \__,_| \___||_| |_|

ForEach - Emulation of for/each logic for TL++

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

#include "totvs.ch"
#include "parmtype.ch"

namespace FWWebEx

#IFNDEF _THASH_CH

    #DEFINE _THASH_CH

    #DEFINE HASH_SECTION_POSITION  1
    #DEFINE HASH_PROPERTY_POSITION 2

    #DEFINE HASH_PROPERTY_KEY      1
    #DEFINE HASH_PROPERTY_VALUE    2
    #DEFINE HASH_PROPERTY_FILE     3
    #DEFINE HASH_PROPERTY_TYPE     4
    #DEFINE HASH_PROPERTY_CLSNAME  5

    #DEFINE HASH_PROPERTY_ELEMENTS 5

    #DEFINE SECTION_POSITION       HASH_SECTION_POSITION
    #DEFINE PROPERTY_POSITION      HASH_PROPERTY_POSITION

    #DEFINE PROPERTY_KEY           HASH_PROPERTY_KEY
    #DEFINE PROPERTY_VALUE         HASH_PROPERTY_VALUE
    #DEFINE PROPERTY_FILE          HASH_PROPERTY_FILE
    #DEFINE PROPERTY_TYPE          HASH_PROPERTY_TYPE
    #DEFINE PROPERTY_CLSNAME       HASH_PROPERTY_CLSNAME

    #DEFINE PROPERTY_ELEMENTS      HASH_PROPERTY_ELEMENTS

    #DEFINE HASH_KEY_POS        1
    #DEFINE HASH_KEY_INDEX      2
    #DEFINE HASH_KEY_ELEMENTS   2

    #DEFINE HASH_KEY_SIZE       6

    #ifndef __CLS_NAME_THASH
        #define __CLS_NAME_THASH
        #define CLS_NAME_THASH "|DNA.TECH.JSONHASH|DNA.TECH.JSONARRAY|DNA.TECH.THASH|DNA.TECH.TFINI|DNA.TECH.THASH_TFINI|"
    #endif

#ENDIF

class ForEach from FWWebEx.ClassBase

    private data aKeys as array

    private data bCallback as codeblock

    private data cType as character
    private data c__ClassName as character

    private data lDescend as logical

    private data nBeg as numeric
    private data nEnd as numeric
    private data nStep as numeric

    private data nIndex as numeric

    private data xKey as variant
    private data xValue as variant
    private data xTarget as variant

    public method New(xTarget as variant,bCallback as codeblock,lDescend as logical) as object

    public method Eval() as variant

    //the hash key value of traversed hash item pair
    public method __enumKey() as variant

    //the value of variable
    public method __enumValue() as variant

    //is it the first enumerated item?
    public method __enumIsFirst() as logical

    //is it the last enumerated item?
    public method __enumIsLast() as logical

    //the loop counter for variable
    public method __enumIndex() as numeric

    //the value that is being traversed
    public method __enumBase()

    private method __arrayIsHashObject(aArray as array) as logical
    private method __arrayIsHashObjectItem(aArray as array) as logical

    static method Evaluate(xTarget as variant,bCallback as codeblock,lDescend as logical) as variant

end class

method New(xTarget,bCallback,lDescend) class ForEach
    paramtype 1 var xTarget as array,character,json,object
    paramtype 2 var bCallback as block
    paramtype 3 var lDescend as logical optional default .F.
    _Super:New()
    ::bCallback:=bCallback
    ::nIndex:=0
    ::xTarget:=xTarget
    ::cType:=ValType(::xTarget)
    ::c__ClassName:=""
    if (::cType=="A")
        ::aKeys:=::xTarget
    elseif (::cType=="C")
        ::aKeys:=Array(Len(::xTarget))
    elseif (::cType=="J")
        ::aKeys:=::xTarget:GetNames()
    elseif (::cType=="O")
        ::c__ClassName:=GetClassName(::xTarget)
        if (::c__ClassName=="THASHMAP")
            ::xTarget:List(@::aKeys)
        else
            if (::c__ClassName$CLS_NAME_THASH)
                if (::c__ClassName=="DNA.TECH.JSONARRAY")
                    ::aKeys:=::xTarget:GetNames()
                elseif (::c__ClassName$"DNA.TECH.THASH|DNA.TECH.TFINI|DNA.TECH.THASH_TFINI")
                    ::aKeys:=::xTarget:GetHashArray()
                else
                    ::aKeys:=Array(0)
                endif
            else
                ::aKeys:=Array(0)
            endif
        endif
    else
        ::aKeys:=Array(0)
    endif

    ::nBeg:=if(lDescend,Len(::aKeys),1)
    ::nEnd:=if(lDescend,1,Len(::aKeys))
    ::nStep:=if(lDescend,(-1),1)

return(self)

method Eval() class ForEach

    local i as numeric

    do case
    case (::cType=="A")
        for i:=::nBeg to ::nEnd step ::nStep
            if ((ValType(::aKeys[i])=="A").and.(::__arrayIsHashObjectItem(::aKeys[i])))
                ::xKey:=::aKeys[i][HASH_PROPERTY_KEY]
                ::xValue:=::aKeys[i][HASH_PROPERTY_VALUE]
            else
                ::xKey:=i
                ::xValue:=::aKeys[i]
            endif
            ::nIndex:=i
            Eval(::bCallback,::xKey,::xValue,::nIndex)
        next i
    case (::cType=="C")
        for i:=::nBeg to ::nEnd step ::nStep
            ::xKey:=i
            ::aKeys[::xKey]:=SubStr(::xTarget,::xKey,1)
            ::xValue:=::aKeys[::xKey]
            ::nIndex:=i
            Eval(::bCallback,::xKey,::xValue,::nIndex)
        next i
    case (::cType=="J")
        for i:=::nBeg to ::nEnd step ::nStep
            ::xKey:=::aKeys[i]
            ::xValue:=::xTarget[::xKey]
            ::nIndex:=i
            Eval(::bCallback,::xKey,::xValue,::nIndex)
        next i
    case (::cType=="O")
        if (::c__ClassName=="THASHMAP")
            for i:=::nBeg to ::nEnd step ::nStep
                ::xKey:=::aKeys[i][HASH_PROPERTY_KEY]
                ::xValue:=::aKeys[i][HASH_PROPERTY_VALUE]
                ::nIndex:=i
                Eval(::bCallback,::xKey,::xValue,::nIndex)
            next i
        elseif (::c__ClassName$CLS_NAME_THASH)
            if (::c__ClassName=="DNA.TECH.JSONARRAY")
                for i:=::nBeg to ::nEnd step ::nStep
                    ::xKey:=::aKeys[i]
                    ::xValue:=::xTarget:Get(::xKey)
                    ::nIndex:=i
                    Eval(::bCallback,::xKey,::xValue,::nIndex)
                next i
            elseif (::c__ClassName$"DNA.TECH.THASH|DNA.TECH.TFINI|DNA.TECH.THASH_TFINI")
                for i:=::nBeg to ::nEnd step ::nStep
                    ::xKey:=::aKeys[i][HASH_PROPERTY_KEY]
                    ::xValue:=::aKeys[i][HASH_PROPERTY_VALUE]
                    ::nIndex:=i
                    Eval(::bCallback,::xKey,::xValue,::nIndex)
                next i
            endif
        endif
    otherwise
        // non-iterable
    endcase

return

//the hash key value of traversed hash item pair
method __enumKey() class ForEach
return(::xKey)

//the value of variable
method __enumValue() class ForEach
return(::xValue)

//is it the first enumerated item?
method __enumIsFirst() class ForEach
return(::nIndex==::nBeg)

//is it the last enumerated item?
method __enumIsLast() class ForEach
return(::nIndex==::nEnd)

//the loop counter for variable
method __enumIndex() class ForEach
return(::nIndex)

//the value that is being traversed
method __enumBase() class ForEach
return(::xTarget)

method __arrayIsHashObject(aArray) class ForEach
    local lIsHashObject as logical
    paramtype 1 var aArray as array
    begin sequence
        lIsHashObject:=(Len(aArray)==HASH_PROPERTY_ELEMENTS)
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(ValType(aArray[HASH_PROPERTY_VALUE])$"ALO")
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(ValType(aArray[HASH_PROPERTY_TYPE])=="C")
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(aArray[HASH_PROPERTY_TYPE]=="O")
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(ValType(aArray[HASH_PROPERTY_CLSNAME])=="C")
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(aArray[HASH_PROPERTY_CLSNAME]$CLS_NAME_THASH)
    end sequence
return(lIsHashObject)

method __arrayIsHashObjectItem(aArray) class ForEach
    local lIsHashObject as logical
    paramtype 1 var aArray as array
    begin sequence
        lIsHashObject:=(Len(aArray)==HASH_PROPERTY_ELEMENTS)
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(;
                 (ValType(aArray[HASH_PROPERTY_TYPE])=="C"));
            .and.(aArray[HASH_PROPERTY_TYPE]$ValType(aArray[HASH_PROPERTY_VALUE]);
        )
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(ValType(aArray[HASH_PROPERTY_CLSNAME])=="C")
        if (!lIsHashObject)
            break
        endif
        lIsHashObject:=(aArray[HASH_PROPERTY_CLSNAME]=="")
    end sequence
return(lIsHashObject)

static method Evaluate(xTarget,bCallback,lDescend) class ForEach
    local oForEach as object
    paramtype 1 var xTarget as array,character,json,object
    paramtype 2 var bCallback as block
    paramtype 3 var lDescend as logical optional default .F.
    oForEach:=ForEach():New(xTarget,bCallback,lDescend)
    oForEach:Eval()
return
