/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

#include "fw.webex.th"

using namespace FWWebEx
using namespace FWWebEx.Tools

/*
    Obs.:   Para chamada atraves do Menu do Protheus inclua FWWeb000 como funcao de usuario
            Em 01/07/2025 as 15:21:10 a equipe da TOTVS ainda nao resolveu a questao de funcoes TLPP com Nomes Longos no MENU.
            Eles poderiam colocar: tlpp.call(<cFunction>,[xParms]) para executar funcoes TL++ em Advpl nas chamadas do MENU.
            Fazer o Q. Bora criar um Wrapper chamado u_FWWeb000.
*/
procedure u_FWWeb000()
    /*
        Assim deveria ser a chamada no MENU:
        tlpp.call("u_FWWebExExample_000")
        Problemas: Quando Erro a Stack nao vem completa.
    */
    u_FWWebExExample_000()
return

procedure u_FWWebExExample_000()

    local aGetSrvInfo as array

    local cEnvServer:=Upper(GetEnvServer()) as character
    local lContinue:=.T. as logical

    aGetSrvInfo:=GetSrvInfo()
    if ((Len(aGetSrvInfo)>=1).and.(aGetSrvInfo[1]=="DNA-TECH-01"))
        lContinue:=(cEnvServer=="PROTHEUS_NGROK")
    endif
    FWFreeArray(@aGetSrvInfo)

    if (!lContinue)
        Final(WebExHelper():Accentuation("Ambiente ["+cEnvServer+"] Inv#1lido.","aacute"),"Utilize o Ambiente: PROTHEUS_NGROK")
    endif

    private cCadastro:="FWWebEx :: Exemplos" as character
    FWExampleTools():Execute({||FWWebExExample_000()},cCadastro,.T.)

return

static procedure FWWebExExample_000()

    local cRight as character
    local cExample:="" as character

    local jFWWebExExamples:=JSONObject():New() as json

    local nTop as numeric
    local nLeft as numeric
    local nBottom as numeric
    local nRight as numeric

    local nExample as numeric
    local nExamples:=32 as numeric

    local oTDlg as object
    local oTMenu as object
    local oTPanel as object
    local oTBitMap as object
    local oFWDefSize as object
    local oWNDDefault as object

    jFWWebExExamples["Games"]:=JSONObject():New()
    TLPPGames(@jFWWebExExamples["Games"])

    jFWWebExExamples["Tools"]:=JSONObject():New()
    TLPPTools(@jFWWebExExamples["Tools"])
    TLPPForEach(@jFWWebExExamples["Tools"])
    TLPPSwitch(@jFWWebExExamples["Tools"])

    jFWWebExExamples["FWWebEx"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Forms"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Tables"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["DataTables"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["UIComponents"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["DashBoard"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Nav"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["DumpDOM"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["iFrame"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["SBAdmin"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Markdown"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["ASCIIArt"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Runtime"]:=JSONObject():New()
    jFWWebExExamples["FWWebEx"]["Labels"]:=JSONObject():New()

    for nExample:=1 to nExamples
        cExample:="u_FWWebExExample_"+StrZero(nExample,3)
        if (!FindFunction(cExample))
            loop
        endif
        cRight:=Right(cExample,3)
        do case
        case (cRight$"003|005|017")
            jFWWebExExamples["FWWebEx"]["Forms"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"001|002|006|007|008|009|018")
            jFWWebExExamples["FWWebEx"]["Tables"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"023|028|029")
            jFWWebExExamples["FWWebEx"]["DataTables"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"004")
            jFWWebExExamples["FWWebEx"]["UIComponents"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"010|011")
            jFWWebExExamples["FWWebEx"]["DashBoard"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"012|013|014")
            jFWWebExExamples["FWWebEx"]["Nav"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"015")
            jFWWebExExamples["FWWebEx"]["DumpDOM"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"016")
            jFWWebExExamples["FWWebEx"]["iFrame"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"019|020|021|022")
            jFWWebExExamples["FWWebEx"]["SBAdmin"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"024")
            jFWWebExExamples["FWWebEx"]["Markdown"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"025|026|030")
            jFWWebExExamples["FWWebEx"]["ASCIIArt"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"027")
            jFWWebExExamples["FWWebEx"]["Runtime"][cExample]:=&("{||"+cExample+"()}")
        case (cRight$"031|032")
            jFWWebExExamples["FWWebEx"]["Labels"][cExample]:=&("{||"+cExample+"()}")
        endcase
    next nExample

    oWNDDefault:=GetWNDDefault()
    if ((Empty(oWNDDefault)).and.(Type("oMainWnd")=="O"))
        oWNDDefault:=oMainWnd
    endif

    oFWDefSize:=FWDefSize():New(.T.,.T.)//Sem enchoicebar
    oFWDefSize:lLateral:=.F.//Calculo vertical
    oFWDefSize:AddObject("TMENU",100,100,.T.,.T.)//TMENU

    oFWDefSize:Process()

    nTop:=oFWDefSize:aWindSize[1]
    nLeft:=oFWDefSize:aWindSize[2]
    nBottom:=oFWDefSize:aWindSize[3]
    nRight:=oFWDefSize:aWindSize[4]

    if ((Type("lRedefineBottom")=="L".and.(lRedefineBottom)))
        nBottom-=50
    endif

    DEFINE MSDIALOG oTDlg TITLE cCadastro FROM nTop,nLeft TO nBottom,nRight PIXEL OF oWNDDefault

        if ((Type("lRedefineBottom")=="L".and.(lRedefineBottom)))
            oTDlg:nTop+=7
            oTDlg:nLeft+=5
            oTDlg:nRight+=0
            oTDlg:nBottom-=11
        endif

        @ 000,000 MSPANEL oTPanel OF oTDlg
        oTPanel:Align:=CONTROL_ALIGN_ALLCLIENT

        @ nTop,nLeft BITMAP oTBitMap RESNAME "DNA_TECH_LOGO_MENU_BACKGROUND_BLACK_PANTER" SIZE nBottom,nRight BORDER OF oTPanel PIXEL
        oTBitMap:lTransparent:=.F.
        oTBitMap:Align:=CONTROL_ALIGN_ALLCLIENT
        oTBitMap:SetCSS("{background-size: 100% 100%;}")

        FWMsgRun(nil,{||oTMenu:=LoadMenu(@oTDlg,jFWWebExExamples)},"Wait! Loading Menu",cCadastro)

        oTDlg:SetMenu(oTMenu)
        oTDlg:lCentered:=((Type("lRedefineBottom")=="L".and.(!lRedefineBottom)))

    ACTIVATE DIALOG oTDlg

    WebFileTools():ObliterateFWWebExTmpFiles(.T.)

    FreeObj(@jFWWebExExamples)

    FreeObj(@oFWDefSize)

    FreeObj(@oTBitMap)
    FreeObj(@oTPanel)
    FreeObj(@oTMenu)
    FreeObj(@oTDlg)

    DelClassIntF()

return

static function LoadMenu(oTDlg as object,jFWWebExExamples as json) as object

    local aNames as array
    local aOwners as array
    local aCategories as array

    local bTMenuAction as codeblock

    local cName as character
    local cOwner as character
    local cCategory as character

    local nName as numeric
    local nNames as numeric

    local nCategory as numeric
    local nCategories as numeric

    local nOwner as numeric
    local nOwners as numeric

    local oTMenu as object
    local oTMenuItem as object

    MENU oTMenu IMAGE "" OF oTDlg
        MENU
            MENUITEM oTMenuItem PROMPT "FWWebEx :: Config"
            oTMenuItem:bAction:={||FWWebEx.Tools.FWExampleTools():GetRESTCredential()}
        ENDMENU
        MENU
            aOwners:=aClone(jFWWebExExamples:GetNames())
            nOwners:=Len(aOwners)
            for nOwner:=1 to nOwners
                cOwner:=aOwners[nOwner]
                MENUITEM oTMenuItem PROMPT cOwner
                MENU
                    aCategories:=aClone(jFWWebExExamples[cOwner]:GetNames())
                    nCategories:=Len(aCategories)
                    for nCategory:=1 to nCategories
                        cCategory:=aCategories[nCategory]
                        MENUITEM oTMenuItem PROMPT cCategory
                        MENU
                            aNames:=aClone(jFWWebExExamples[cOwner][cCategory]:GetNames())
                            nNames:=Len(aNames)
                            for nName:=1 to nNames
                                cName:=aNames[nName]
                                bTMenuAction:=jFWWebExExamples[cOwner][cCategory][cName]
                                MENUITEM oTMenuItem PROMPT cName
                                oTMenuItem:bAction:=bTMenuAction
                            next nName
                            FWFreeArray(@aNames)
                        ENDMENU
                    next nCategory
                    FWFreeArray(@aCategories)
                ENDMENU
            next nOwner
            FWFreeArray(@aOwners)
        ENDMENU
        MENU
            MENUITEM oTMenuItem PROMPT "Exit" ACTION if(ApMsgNoYes("Deseja sair?","FWWebEx"),oTDlg:End(),.F.)
        ENDMENU
    ENDMENU

    oTMenu:align:=CONTROL_ALIGN_ALLCLIENT

return(oTMenu)

static procedure TLPPTools(jFWWebExExamples)
    jFWWebExExamples["TLPPTools"]:=JSONObject():New()
    jFWWebExExamples["TLPPTools"]["ArrayTools"]:={||u_ArrayToolsSample()}
    jFWWebExExamples["TLPPTools"]["FlattenJSON"]:={||u_FlattenJSONSample()}
return

static procedure TLPPGames(jFWWebExExamples as json)

    local aTLPPGames:={;
        {"GAME15.U_GAME15RUN","GAME15",{||GAME15.U_GAME15RUN()}};
       ,{"SUDOKU.U_SUDOKURUN","SUDOKU",{||SUDOKU.U_SUDOKURUN()}};
       ,{"SUDOKU.U_SUDOKURUNTESTS","SUDOKURUNTESTS",{||SUDOKU.U_SUDOKURUNTESTS()}};
       ,{"SAPURECA.U_SAPURECARUN","SAPURECA",{||SAPURECA.U_SAPURECARUN()}};
    }

    local lTlppGame as logical

    local nGame, nGames as numeric

    nGames:=Len(aTLPPGames)
    for nGame:=1 to nGames
        lTlppGame:=FindFunction(aTLPPGames[nGame][1])
        if (lTlppGame)
            exit
        endif
    next nGame

    if (lTlppGame)
        jFWWebExExamples["TLPPGames"]:=JSONObject():New()
        for nGame:=1 to nGames
            lTlppGame:=FindFunction(aTLPPGames[nGame][1])
            if (lTlppGame)
                jFWWebExExamples["TLPPGames"][aTLPPGames[nGame][2]]:=aTLPPGames[nGame][3]
            endif
        next nGame
    endif

    FWFreeArray(@aTLPPGames)

return

static procedure TLPPForEach(jFWWebExExamples)
    if (FindFunction("FWWebEx.U_FOREACHTST"))
        jFWWebExExamples["TLPPForEach"]:=JSONObject():New()
        jFWWebExExamples["TLPPForEach"]["U_FOREACHTST"]:={||U_FOREACHTST()}
    endif
return

static procedure TLPPSwitch(jFWWebExExamples)
    if (FindFunction("FWWebEx.U_SWITCHTST"))
        jFWWebExExamples["TLPPSwitch"]:=JSONObject():New()
        jFWWebExExamples["TLPPSwitch"]["U_SWITCHTST"]:={||U_SWITCHTST()}
    endif
return
