/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

The source code `fw.webex.example.tools.tlpp` is based on more detailed and feature-rich sources:
    `dna.tech.mainexec.tlpp`
   ,`dna.tech.txteditmemo.tlpp`
   ,`dna.tech.sqltools.tlpp`
- and implements part of the functionalities present in these.

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

namespace FWWebEx.Tools

using namespace FWWebEx
using namespace FWWebEx.Tools

#include "fw.webex.th"

#define __PARAM_CLIENT_ID__ 1
#define __PARAM_CLIENT_SECRET__ 2
#define __PARAM_USER_NAME__ 3
#define __PARAM_PASSWORD__ 4
#define __PARAM_REST_URL__ 5
#define __PARAM_USE_OAUTH2__ 6
#define __PARAM_REST_URL_OAUTH2__ 7
#define __PARAM_APPROOT_URI__ 8

static __cUserID as character
static __cClientSecret as character
static __cUserName as character
static __cUserPassWord as character

class FWExampleTools

    static method Execute(bExecute as codeblock,cTitle as character,lPrepareEnvironment as logical,lChangeCompanyAndBranch as logical) as variant
    static method HtmlFileShow(cHTML as character,cTitle as character,cHTMLFile as character,bJSToAdvPL as codeblock,bCallBack as codeblock,cCallBackActRet as character) as variant

    static method GetRESTCredential(cUSR as character,cPDW as character,cRESTURL as character,lUseOAuth2 as logical) as logical
    static method EnableRESTCredentialParameters() as logical

    static method ChangeCompanyAndBranch(cCompany as character,cBranch as character,lFirstAccess as logical,cStack as character)

    static method NoCheckUri() as array
    static method ValidaToken(cToken,cPath) as logical
    static method ParamsProvider() as json

    static method GetClientID(cUserID as character) as character
    static method GetClientSecret(cClientSecret as character) as character
    static method GetUserName(cUserName as character) as character
    static method GetUserPassWord(cUserPassWord as character) as character
    static method GetAuthorization(cUSR as character,cPDW as character,cRESTURLOAuth2 as character) as json

    //https://startbootstrap.com/template/sb-admin
    static method SBAdminCheck() as logical

endclass

static method Execute(bExecute,cTitle,lPrepareEnvironment,lChangeCompanyAndBranch) class FWExampleTools

    local bInit as codeblock

    local cEmp as character
    local cFil as character

    local lMainWnd as logical
    local lSetCentury:=__SetCentury("ON") as logical

    local oMainBmp as object
    local oMainPanel as object

    paramtype 1 var bExecute as block
    paramtype 2 var cTitle as character optional default ProcName(1)
    paramtype 3 var lPrepareEnvironment as logical optional default .F.
    paramtype 4 var lChangeCompanyAndBranch as logical optional default .F.

    private lRedefineBottom as logical

    bInit:={||;
         if(lChangeCompanyAndBranch,FWExampleTools():ChangeCompanyAndBranch(@cEmp,@cFil,.T.,ProcName()),nil);
        ,Eval(bExecute);
    }

    lMainWnd:=(Type("oMainWnd")=="O")
    if (!lMainWnd)
        if (lPrepareEnvironment)
            OpenSM0()
            SM0->(dbGoTop())
            cEmp:=SM0->M0_CODIGO
            cFil:=SM0->M0_CODFIL
            FWMsgRun(nil,{||RPCSetEnv(cEmp,cFil,GetEnvServer())},"Wait...","Preparing environment")
            cEmp:=cEmpAnt
            cFil:=cFilAnt
            if ((Type("__cInternet")=="C").and.(__cInternet=="AUTOMATICO"))
                //Redefine modo Blind
                __cInternet:=NIL
            endif
            SetsDefault()
            lSetCentury:=__SetCentury("ON")
        endif
            if (WebApp():WebAgentIsConnected())
                private oMainWnd as object
                lRedefineBottom:=.T.
                DEFINE WINDOW oMainWnd FROM 00,00 TO 1024,768 TITLE cTitle
                    @ 000,000 MSPANEL oMainPanel OF oMainWnd
                    oMainPanel:Align:=CONTROL_ALIGN_ALLCLIENT
                    @ 000,000 BITMAP oMainBmp RESNAME "DNA_TECH_LOGO_BLACK_PANTER" SIZE 1024,1024 BORDER OF oMainPanel PIXEL
                    oMainBmp:Align:=CONTROL_ALIGN_ALLCLIENT
                    oMainBmp:SetCSS("{background-size: 100% 100%;}")
                ACTIVATE WINDOW oMainWnd MAXIMIZED ON INIT (Eval(bInit),oMainWnd:End())
                FreeObj(@oMainBmp)
                FreeObj(@oMainPanel)
                FreeObj(@oMainWnd)
            else
                ApMsgAlert("WebAgent is not connected",ProcName())
            endif
        if (lPrepareEnvironment)
            RPCClearEnv()
        endif
    else
        lRedefineBottom:=(FWIsInCallStack("u_FWWebExExample_000"))
        cEmp:=cEmpAnt
        cFil:=cFilAnt
        if (WebApp():WebAgentIsConnected())
            Eval(bInit)
        else
            ApMsgAlert("WebAgent is not connected",ProcName())
        endif
    endif

    if (!lSetCentury)
        __SetCentury("OFF")
    endif

return

static method HtmlFileShow(cHTML,cTitle,cHTMLFile,oTWebChannel,bJSToAdvPL,bCallBack,cCallBackActRet) class FWExampleTools

    local aButtons as array
    local aButtonsObj as array

    local bDialogInit as codeblock
    local bErrorBlock as codeblock

    local cHTMLFileTmpFile as character
    local cHTMLFileServer as character
    local cHTMLFileNavigate as character

    local jSplitPath as json

    local lAbrir as logical
    local lTWebChannel as logical

    local nTop as numeric
    local nLeft as numeric
    local nBottom as numeric
    local nRight as numeric

    local oDlg as object
    local oError as object
    local oFWDefSize as object
    local oTWebEngine as object

    paramtype 1 var cHTML as character
    paramtype 2 var cTitle as character
    paramtype 3 var cHTMLFile as character
    paramtype 3 var oTWebChannel as object class TWEBCHANNEL optional
    paramtype 4 var bJSToAdvPL as block optional
    paramtype 5 var bCallBack as block optional
    paramtype 6 var cCallBackActRet as character optional

    lTWebChannel:=(ValType(oTWebChannel)=="O")

    begin sequence

        if (!lTWebChannel)
            oTWebChannel:=TWebChannel():New()
            oTWebChannel:Connect()
        endif

        if (!oTWebChannel:lConnected)
            oTWebChannel:Connect()
            if (!oTWebChannel:lConnected)
                ApMsgInfo("Falha ao Conectar ao WebSocket",ProcName())
                break
            endif
        endif

        if (ValType(bJSToAdvPL)=="B")
            oTWebChannel:bJSToAdvPL:=bJSToAdvPL
        endif

        if (ValType(bCallBack)=="B")
            oTWebChannel:bSetGet:=bCallBack
        endif

        if (ValType(cCallBackActRet)=="C")
            oTWebChannel:cMSG:=cCallBackActRet
        endif

        aButtons:=array(0)
        aAdd(aButtons,{"&Print",{||oTWebEngine:Print()},OemToAnsi("Print"),OemtoAnsi("Print")})
        aAdd(aButtons,{"Print PD&F",{||oTWebEngine:PrintPDF()},OemToAnsi("Print PDF"),OemtoAnsi("Print PDF")})

        lAbrir:=file(cHTMLFile)

        if (lAbrir)
            lAbrir:=(WebApp():WebAgentIsConnected())
            if (WebApp():WebAgentIsConnected())
                bErrorBlock:=ErrorBlock({|oError|Break(oError)})
                begin sequence
                    //CpyF2Web(<cOrigem>,[lIsUserDiskDir],[lCompactCopy],[lChangeCase],[lUnZipFile])
                    cHTMLFileNavigate:=CpyF2Web(cHTMLFile,.T.,.T.,.F.,.F.)
                recover
                    begin sequence
                        //CpyF2Web(<cOrigem>,[lIsUserDiskDir],[lCompactCopy],[lChangeCase],[lUnZipFile])
                        cHTMLFileNavigate:=CpyF2Web(cHTMLFile,.F.,.T.,.F.,.F.)
                    end sequence
                end sequence
                ErrorBlock(bErrorBlock)
                if ((Empty(cHTMLFileNavigate)).and.(lIsDir(FWWEBEX_WEB_TMP_PATH)))
                    jSplitPath:=WebFileTools():SplitPath(cHTMLFile)
                        cHTMLFileServer:=FWWEBEX_WEB_TMP_PATH
                        cHTMLFileServer+=jSplitPath["file"]
                        cHTMLFileServer+=jSplitPath["ext"]
                        cHTMLFileNavigate:=cHTMLFileServer
                    FreeObj(@jSplitPath)
                    bErrorBlock:=ErrorBlock({|oError|Break(oError)})
                    begin sequence
                        //CpyF2Web(<cOrigem>,[lIsUserDiskDir],[lCompactCopy],[lChangeCase],[lUnZipFile])
                        cHTMLFileNavigate:=CpyF2Web(cHTMLFileNavigate,.T.,.T.,.F.,.F.)
                    recover
                        begin sequence
                            //CpyF2Web(<cOrigem>,[lIsUserDiskDir],[lCompactCopy],[lChangeCase],[lUnZipFile])
                            cHTMLFileNavigate:=CpyF2Web(cHTMLFileNavigate,.F.,.T.,.F.,.F.)
                        recover
                            cHTMLFileNavigate:=cHTMLFileServer
                        end sequence
                    end sequence
                    ErrorBlock(bErrorBlock)
                endif
                jSplitPath:=WebFileTools():SplitPath(cHTMLFile)
                    cHTMLFileTmpFile:=GetTempPath()
                    cHTMLFileTmpFile+=jSplitPath["file"]
                    cHTMLFileTmpFile+=jSplitPath["ext"]
                FreeObj(@jSplitPath)
                WebFileTools():CopyFile(cHTMLFile,cHTMLFileTmpFile)
                aAdd(aButtons,{"&Abrir",{||ShellExecute("open",cHTMLFileTmpFile,"","",SW_SHOWMAXIMIZED)},OemToAnsi("Abir"),OemtoAnsi("Abir")})
                aAdd(aButtons,{"Go&Back",{||oTWebEngine:GoBack()},OemToAnsi("Go Back"),OemtoAnsi("Go Back")})
                aAdd(aButtons,{"Go&Home",{||oTWebEngine:GoHome()},OemToAnsi("Go Home"),OemtoAnsi("Go Home")})
                aAdd(aButtons,{"Go&Forward",{||oTWebEngine:GoForward()},OemToAnsi("Go Forward"),OemtoAnsi("Go Forward")})
            endif
        endif

        aAdd(aButtons,{"&Sair",{||oDlg:End()},OemToAnsi("Sair"),OemtoAnsi("Sair")})

        oFWDefSize:=FWDefSize():New(.F.,.F.)
        oFWDefSize:lLateral:=.F.
        oFWDefSize:AddObject("TWebEngine",100,100,.T.,.T.)

        oFWDefSize:Process()

        if (oFWDefSize:aWindSize[3]==0)
            nTop:=0
            nLeft:=0
            nBottom:=530
            nRight:=1330
        else
            nTop:=oFWDefSize:aWindSize[1]
            nLeft:=oFWDefSize:aWindSize[2]
            nBottom:=oFWDefSize:aWindSize[3]
            nRight:=oFWDefSize:aWindSize[4]
        endif

        if (Type("lRedefineBottom")!="L")
            private lRedefineBottom:=.T. as logical
        endif

        if (lRedefineBottom)
            nBottom-=15
        endif

        DEFINE MSDIALOG oDlg TITLE cTitle FROM nTop,nLeft TO nBottom,nRight OF GetWndDefault() STATUS PIXEL

            if (oFWDefSize:aWindSize[3]>0)
                nTop:=oFWDefSize:GetDimension("TWebEngine","LININI")
                nLeft:=oFWDefSize:GetDimension("TWebEngine","COLINI")
                nBottom:=oFWDefSize:GetDimension("TWebEngine","LINEND")
                nRight:=oFWDefSize:GetDimension("TWebEngine","COLEND")
                nTop-=5
                nBottom+=1
                nRight-=5
                if (lRedefineBottom)
                    nBottom-=25
                endif
            endif

            oTWebEngine:=TWebEngine():New(oDlg,nTop,nLeft,nRight,nBottom,/*cURL*/,oTWebChannel:nPort)
            oTWebEngine:Align:=CONTROL_ALIGN_ALLCLIENT
            WebApp():SetTWebEngine(oTWebEngine)

            oDlg:lEscClose:=.F.

            oTWebEngine:Navigate(cHTMLFileNavigate)

            oDlg:lCentered:=(!lRedefineBottom)

            bDialogInit:={||aButtonsObj:=FWWebEx.Tools.ButtonBar():BuildTopButtonBar(oDlg,aButtons,nTop,nRight,nil,nil,3/*nButtonCol*/,65/*nButtonSize*/,15/*nButtonHeight*/,.F./*lAddOkCancelButtons*/)}

        ACTIVATE MSDIALOG oDlg ON INIT Eval(bDialogInit)

        FWWebEx.Tools.ButtonBar():CleanButtonBar(@aButtonsObj)

        if ((!lTWebChannel).and.(valType(oTWebChannel)=="O"))
            oTWebChannel:Disconnect()
        endif

        if ((!Empty(cHTMLFile)).and.(File(cHTMLFile)))
            fErase(cHTMLFile)
        endif

        if ((!Empty(cHTMLFileNavigate)).and.(File(cHTMLFileNavigate)))
            fErase(cHTMLFileNavigate)
        endif

        if ((!Empty(cHTMLFileServer)).and.(File(cHTMLFileServer)))
            fErase(cHTMLFileServer)
        endif

        if ((!Empty(cHTMLFileTmpFile)).and.(File(cHTMLFileTmpFile)))
            fErase(cHTMLFileTmpFile)
        endif

    end sequence

    FWFreeArray(@aButtons)

    FreeObj(@oDlg)
    FreeObj(@oFWDefSize)

    FreeObj(@oTWebEngine)
    if (!lTWebChannel)
        FreeObj(@oTWebChannel)
    endif

    DelClassIntF()

return

static method GetRESTCredential(cUSR,cPDW,cRESTURL,cRESTURLOAuth2,jGetAuthorization,lUseOAuth2) class FWExampleTools

    local aPBoxPrm:=Array(0) as array
    local aPBoxRet:=Array(0) as array

    local cStack:=ProcName() as character
    local cAppRootURI as character

    local cClientID as character
    local cClientSecret as character
    local cEnvServer:=GetEnvServer() as character
    local cSRVIniName:=GetSrvIniName() as character

    local lChangeParameters as logical
    local lGetRESTCredential as logical

    local oParamBoxLoad as object

    paramtype 1 var cUSR as character optional default AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"UserName","",cSRVIniName))
    paramtype 2 var cPDW as character optional default AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"Password","",cSRVIniName))
    paramtype 3 var cRESTURL as character optional default AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"RestURL","",cSRVIniName))
    paramtype 4 var cRESTURLOAuth2 as character optional default AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"OAuth2URL","",cSRVIniName))
    paramtype 5 var jGetAuthorization as json optional
    paramtype 6 var lUseOAuth2 as logical optional default .F.

    cAppRootURI:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"AppRootURI","",cSRVIniName))
    cAppRootURI:=PadR(cAppRootURI,200)

    cClientID:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"ClientID","",cSRVIniName))
    if (Empty(cClientID))
        cClientID:=__cUserID
    endif
    cClientID:=PadR(cClientID,100)

    cClientSecret:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"ClientSecret","",cSRVIniName))
    if (Empty(cClientSecret))
        cClientSecret:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"Password","",cSRVIniName))
    endif
    cClientSecret:=PadR(cClientSecret,100)

    if (Empty(cUSR))
        cUSR:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"UserName","",cSRVIniName))
    endif
    cUSR:=PadR(cUSR,100)
    if (Empty(cPDW))
        cPDW:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"Password","",cSRVIniName))
    endif

    cPDW:=PadR(cPDW,100)
    if (Empty(cRESTURL))
        cRESTURL:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"RestURL","",cSRVIniName))
    endif
    cRESTURL:=PadR(cRESTURL,200)

    if (Empty(cRESTURLOAuth2))
        cRESTURLOAuth2:=AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"OAuth2URL","",cSRVIniName))
    endif
    cRESTURLOAuth2:=PadR(cRESTURLOAuth2,200)

    begin sequence

        SaveInter()
            MV_PAR06:=.F.
            /*-----------------------------------------------------------------------------------------------------------------------------------*/
            aAdd(aPBoxPrm,{1,"ClientID",cClientID,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",100,.T.})
            aAdd(aPBoxPrm,{1,"ClientSecret",cClientSecret,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",100,.T.})
            aAdd(aPBoxPrm,{1,"UserName",cUSR,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",100,.T.})
            aAdd(aPBoxPrm,{1,"Password",cPDW,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",100,.T.})
            aAdd(aPBoxPrm,{1,"URL REST",cRESTURL,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",200,.T.})
            aAdd(aPBoxPrm,{4,"OAuth2",MV_PAR06,"",100,"FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",.F.})
            aAdd(aPBoxPrm,{1,"URL REST OAuth2",cRESTURLOAuth2,"@","IF(MV_PAR06,NaoVazio(),FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters())","","MV_PAR06",200,.T.})
            aAdd(aPBoxPrm,{1,"APPRoot URI",cAppRootURI,"@","NaoVazio()","","FWWebEx.Tools.FWExampleTools():EnableRESTCredentialParameters()",200,.T.})
            /*-----------------------------------------------------------------------------------------------------------------------------------*/
            cStack+=("_"+cEnvServer)
            oParamBoxLoad:=ParamBoxLoad():New(cStack/*cLoad*/,.T./*lCanSave*/,.T./*lUserSave*/)
            MV_PAR01:=oParamBoxLoad:ParamLoad(aPBoxPrm,1,cClientID/*xDefault*/,.F./*lDefault*/)
            MV_PAR02:=oParamBoxLoad:ParamLoad(aPBoxPrm,2,cClientSecret/*xDefault*/,.F./*lDefault*/)
            MV_PAR03:=oParamBoxLoad:ParamLoad(aPBoxPrm,3,cUSR/*xDefault*/,.F./*lDefault*/)
            MV_PAR04:=oParamBoxLoad:ParamLoad(aPBoxPrm,4,cPDW/*xDefault*/,.F./*lDefault*/)
            MV_PAR05:=oParamBoxLoad:ParamLoad(aPBoxPrm,5,cRESTURL/*xDefault*/,.F./*lDefault*/)
            MV_PAR06:=oParamBoxLoad:ParamLoad(aPBoxPrm,6,MV_PAR06/*xDefault*/,.F./*lDefault*/)
            MV_PAR07:=oParamBoxLoad:ParamLoad(aPBoxPrm,7,cRESTURLOAuth2/*xDefault*/,.F./*lDefault*/)
            MV_PAR08:=oParamBoxLoad:ParamLoad(aPBoxPrm,8,cAppRootURI/*xDefault*/,.F./*lDefault*/)
            /*-----------------------------------------------------------------------------------------------------------------------------------*/
            lChangeParameters:=FWExampleTools():EnableRESTCredentialParameters()
            lGetRESTCredential:=ParamBox(@aPBoxPrm,"Selecione os Parametros",@aPBoxRet,/*bOk*/,/*aButtons*/,.T./*lCentered*/,/*nPosx*/,/*nPosy*/,/*oDlgWizard*/,oParamBoxLoad:GetParamLoad()/*cLoad*/,oParamBoxLoad:GetCanSave()/*lCanSave*/,oParamBoxLoad:GetUserSave()/*lUserSave*/)
            if (lGetRESTCredential)
                oParamBoxLoad:ParamSave(aPBoxPrm)
                oParamBoxLoad:ParamReLoad(aPBoxPrm,@aPBoxRet,.F.)
            endif
        RestInter()

        if (!lGetRESTCredential)
            break
        endif

        cClientID:=AllTrim(aPBoxRet[__PARAM_CLIENT_ID__])
        if (empty(cClientID))
            cClientID:=__cUserID
        endif
        if (lChangeParameters)
            if (!(Upper(cClientID)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"ClientID","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"ClientID",cClientID,cSRVIniName)
            endif
        endif
        FWExampleTools():GetClientID(cClientID)

        cClientSecret:=AllTrim(aPBoxRet[__PARAM_CLIENT_SECRET__])
        if (empty(cClientSecret))
            cClientSecret:=AllTrim(aPBoxRet[__PARAM_PASSWORD__])
        endif
        if (lChangeParameters)
            if (!(Upper(cClientSecret)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"ClientSecret","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"ClientSecret",cClientSecret,cSRVIniName)
            endif
        endif
        FWExampleTools():GetClientSecret(cClientSecret)

        cUSR:=AllTrim(aPBoxRet[__PARAM_USER_NAME__])
        if (lChangeParameters)
            if (!(Upper(cUSR)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"UserName","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"UserName",cUSR,cSRVIniName)
            endif
        endif
        FWExampleTools():GetUserName(cUSR)

        cPDW:=AllTrim(aPBoxRet[__PARAM_PASSWORD__])
        if (lChangeParameters)
            if (!(Upper(cPDW)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"Password","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"Password",cPDW,cSRVIniName)
            endif
        endif
        FWExampleTools():GetUserPassWord(cPDW)

        cRESTURL:=AllTrim(aPBoxRet[__PARAM_REST_URL__])
        if (Right(cRESTURL,1)!="/")
            cRESTURL+="/"
        endif
        if (lChangeParameters)
            if (!(Upper(cRESTURL)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"RestURL","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"RestURL",cRESTURL,cSRVIniName)
            endif
        endif

        lUseOAuth2:=aPBoxRet[__PARAM_USE_OAUTH2__]
        if (lUseOAuth2)
            cRESTURLOAuth2:=AllTrim(aPBoxRet[__PARAM_REST_URL_OAUTH2__])
            lUseOAuth2:=(!Empty(cRESTURLOAuth2))
            if (lUseOAuth2)
                if (Right(cRESTURLOAuth2,1)=="/")
                    cRESTURL:=SubStr(cRESTURLOAuth2,1,Len(cRESTURLOAuth2)-1)
                endif
                if (lChangeParameters)
                    if (!(Upper(cRESTURLOAuth2)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"OAuth2URL","",cSRVIniName)))))
                        WritePProString("FWWEBEX_"+cEnvServer,"OAuth2URL",cRESTURLOAuth2,cSRVIniName)
                    endif
                endif
            endif
        endif

        cAppRootURI:=AllTrim(aPBoxRet[__PARAM_APPROOT_URI__])
        if (Right(cAppRootURI,1)!="/")
            cAppRootURI+="/"
        endif
        if (lChangeParameters)
            if (!(Upper(cAppRootURI)==Upper(AllTrim(GetPvProfString("FWWEBEX_"+cEnvServer,"AppRootURI","",cSRVIniName)))))
                WritePProString("FWWEBEX_"+cEnvServer,"AppRootURI",cAppRootURI,cSRVIniName)
            endif
        endif

        jGetAuthorization:=FWExampleTools():GetAuthorization(cUSR,cPDW,cRESTURLOAuth2)

    end sequence

    FWFreeArray(@aPBoxPrm)
    FWFreeArray(@aPBoxRet)
    FreeObj(@oParamBoxLoad)

return(lGetRESTCredential)

static method EnableRESTCredentialParameters() class FWExampleTools
    local cEnvServer as character
    local cSRVIniName as character
    local cComputerName as character
    local lChangeParameters as logical
    //So permite alterar as configuracoes no servidor
    cComputerName:=Upper(AllTrim(GetComputerName()))
    lChangeParameters:=(cComputerName==Upper(AllTrim(GetSrvInfo()[1])))
    if (!lChangeParameters)
        cEnvServer:=GetEnvServer()
        cSRVIniName:=GetSrvIniName()
        lChangeParameters:=(cComputerName$GetPvProfString("FWWEBEX_"+cEnvServer,"EnableRESTCredentialParameters","",cSRVIniName))
    endif
return(lChangeParameters)

//https://tdn.totvs.com/display/tec/onAuthNoCheckUri
static method NoCheckUri() class FWExampleTools
    local aNoCheckUri:=array(0) as array
return(aNoCheckUri)

//https://tdn.totvs.com/pages/viewpage.action?pageId=579117088
static method ValidaToken(cToken,cPath) class FWExampleTools
return(.T.)

//https://tdn.totvs.com/display/tec/onAuthparams
static method ParamsProvider() class FWExampleTools
return(WebAuthorization():ParamsProvider())

static method GetClientID(cUserID) class FWExampleTools
    local cEnvServer:=GetEnvServer() as character
    local cSRVIniName:=GetSrvIniName() as character
    if (!Empty(cUserID))
        __cUserID:=cUserID
    endif
    if (empty(__cUserID))
        __cUserID:=GetPvProfString("FWWEBEX_"+cEnvServer,"ClientID","",cSRVIniName)
    endif

return(__cUserID)

static method GetClientSecret(cClientSecret) class FWExampleTools
    local cEnvServer:=GetEnvServer() as character
    local cSRVIniName:=GetSrvIniName() as character
    if (!Empty(cClientSecret))
        __cClientSecret:=cClientSecret
    endif
    if (empty(__cClientSecret))
        __cClientSecret:=GetPvProfString("FWWEBEX_"+cEnvServer,"ClientSecret","",cSRVIniName)
    endif
return(__cClientSecret)

static method GetUserName(cUserName) class FWExampleTools
    local cEnvServer:=GetEnvServer() as character
    local cSRVIniName:=GetSrvIniName() as character
    if (!Empty(cUserName))
        __cUserName:=cUserName
    endif
    if (empty(__cUserName))
        __cUserName:=GetPvProfString("FWWEBEX_"+cEnvServer,"UserName","",cSRVIniName)
    endif
return(__cUserName)

static method GetUserPassWord(cUserPassWord) class FWExampleTools
    local cEnvServer:=GetEnvServer() as character
    local cSRVIniName:=GetSrvIniName() as character
    if (!Empty(cUserPassWord))
        __cUserPassWord:=cUserPassWord
    endif
    if (empty(__cUserPassWord))
        __cUserPassWord:=GetPvProfString("FWWEBEX_"+cEnvServer,"Password","",cSRVIniName)
    endif
return(__cUserPassWord)

static method GetAuthorization(cUSR,cPDW,cRESTURLOAuth2) class FWExampleTools
    local jGetAuthorization as json
    paramtype 1 var cUSR as character optional default FWExampleTools():GetUserName()
    paramtype 2 var cPDW as character optional default FWExampleTools():GetUserPassWord()
    paramtype 3 var cRESTURLOAuth2 as character optional default ""
    jGetAuthorization:=WebAuthorization():GetAuthorization(cUSR,cPDW,cRESTURLOAuth2)
return(jGetAuthorization)

static method ChangeCompanyAndBranch(cCompany,cBranch,lFirstAccess,cStack) class FWExampleTools

    local aPBoxPrm as array
    local aPBoxRet as array
    local aModulos as array
    local aRetModName as array

    local bParamBoxOK as codeblock

    local aTCSQLToArr as array
    local aSXBDBStruct as array
    local aTCSQLSetFields as array

    local cEnvServer:=GetEnvServer() as character

    local cCSXBAlias as character
    local cBSXBAlias as character
    local cSXBAliasSeek as character
    local cSXBTableName as character
    local cSXBTableQuery as character

    local nSXBItem as numeric
    local nSXBItens as numeric
    local nSXBField as numeric
    local nSXBFields as numeric
    local nTCSQLToArr as numeric
    local nATModulo:=nModulo as numeric

    local lIsBlind:=IsBlind() as logical
    local lChangeOK as logical
    local lRPCTools as logical
    local lParamBox:=.T. as logical
    local lAllModulos:=.F. as logical

    local nPBox as numeric

    local oParamBoxLoad as object

    paramtype 1 var cCompany as character optional default cEmpAnt
    paramtype 2 var cBranch as character optional default cFilAnt
    paramtype 3 var lFirstAccess as logical optional default .F.
    paramtype 4 var cStack as character optional default "fwwebex_"+Lower(ProcName())

    if (!lIsBlind)

        //Reseta UniqueKey do Filtro SXB
        UniqueKey()

        //Cria a Consulta Padrao %SM0_C se nao existir
        SXB->(dbSetOrder(1))
        cCSXBAlias:=PadR("%SM0_C",Len(SXB->XB_ALIAS))
        cSXBAliasSeek:=cCSXBAlias
        if (SXB->(!dbSeek(cSXBAliasSeek,.F.)))
            cSXBAliasSeek:=PadR("YM0",Len(SXB->XB_ALIAS))
            aSXBDBStruct:=SXB->(dbStruct())
            nSXBFields:=Len(aSXBDBStruct)
            cSXBFields:=""
            for nSXBField:=1 to nSXBFields
                cSXBFields+=aSXBDBStruct[nSXBField][DBS_NAME]
                if (nSXBField<nSXBFields)
                    cSXBFields+=","
                endif
            next nSXBField
            if (SXB->(dbSeek(cSXBAliasSeek,.F.)))
                cSXBTableName:="SXB"+cEmpAnt+"0"
                beginContent var cSXBTableQuery
SELECT cSXBFields
  FROM cSXBTableName SXB
 WHERE SXB.D_E_L_E_T_<>'*'
   AND SXB.XB_ALIAS='cSXBAliasSeek'
                endContent
                cSXBTableQuery:=WebExHelper():StrReplace(;
                    cSXBTableQuery;
                    ,{;
                        "cSXBFields":cSXBFields;
                       ,"cSXBTableName":cSXBTableName;
                       ,"cSXBAliasSeek":cSXBAliasSeek;
                    };
                )
                aTCSQLToArr:=Array(0)
                aTCSQLSetFields:=Array(0)
                aEval(aSXBDBStruct,{|e|if(e[DBS_TYPE]!="C",aAdd(aTCSQLSetFields,e),nil)})
                nTCSQLToArr:=TCSQLToArr(cSXBTableQuery,@aTCSQLToArr,nil,aTCSQLSetFields,aSXBDBStruct)
                nSXBItens:=Len(aTCSQLToArr)
                for nSXBItem:=1 to nSXBItens
                    if (SXB->(RecLock("SXB",.T.)))
                        for nSXBField:=1 to nSXBFields
                            if (SXB->(aSXBDBStruct[nSXBField][DBS_NAME]=="XB_ALIAS"))
                                SXB->XB_ALIAS:=cCSXBAlias
                            elseif (SXB->((aSXBDBStruct[nSXBField][DBS_NAME]=="XB_CONTEM").and.(SXB->XB_TIPO=="6")))
                                SXB->(FieldPut(nSXBField,('SM0->(M0_CODFIL==MV_PAR02.AND.UniqueKey("M0_CODIGO","SM0"))')))
                            else
                                SXB->(FieldPut(nSXBField,aTCSQLToArr[nSXBItem][nSXBField]))
                            endif
                        next nSXBField
                        SXB->(MsUnLock())
                    endif
                next nSXBItem
                cSXBAliasSeek:=cCSXBAlias
                cSXBAliasSeek+="2"
                cSXBAliasSeek+="01"
                cSXBAliasSeek+="01"
                if (SXB->(!dbSeek(cSXBAliasSeek,.F.)))
                    if (SXB->(RecLock("SXB",.T.)))
                        SXB->XB_ALIAS:=cCSXBAlias
                        SXB->XB_TIPO:="2"
                        SXB->XB_SEQ:="01"
                        SXB->XB_COLUNA:="01"
                        SXB->XB_DESCRI:="Codigo"
                        SXB->XB_DESCSPA:="Codigo"
                        SXB->XB_DESCENG:="Code"
                        SXB->(MsUnLock())
                    endif
                endif
            endif
        endif

        //Cria a Consulta Padrao %SM0_B se nao existir
        SXB->(dbSetOrder(1))
        cBSXBAlias:=PadR("%SM0_B",Len(SXB->XB_ALIAS))
        cSXBAliasSeek:=cBSXBAlias
        if (SXB->(!dbSeek(cSXBAliasSeek,.F.)))
            cSXBAliasSeek:=PadR("NGD",Len(SXB->XB_ALIAS))
            aSXBDBStruct:=SXB->(dbStruct())
            nSXBFields:=Len(aSXBDBStruct)
            cSXBFields:=""
            for nSXBField:=1 to nSXBFields
                cSXBFields+=aSXBDBStruct[nSXBField][DBS_NAME]
                if (nSXBField<nSXBFields)
                    cSXBFields+=","
                endif
            next nSXBField
            if (SXB->(dbSeek(cSXBAliasSeek,.F.)))
                cSXBTableName:="SXB"+cEmpAnt+"0"
                beginContent var cSXBTableQuery
SELECT cSXBFields
  FROM cSXBTableName SXB
 WHERE SXB.D_E_L_E_T_<>'*'
   AND SXB.XB_ALIAS='cSXBAliasSeek'
                endContent
                cSXBTableQuery:=WebExHelper():StrReplace(;
                    cSXBTableQuery;
                    ,{;
                        "cSXBFields":cSXBFields;
                       ,"cSXBTableName":cSXBTableName;
                       ,"cSXBAliasSeek":cSXBAliasSeek;
                    };
                )
                aTCSQLToArr:=Array(0)
                aTCSQLSetFields:=Array(0)
                aEval(aSXBDBStruct,{|e|if(e[DBS_TYPE]!="C",aAdd(aTCSQLSetFields,e),nil)})
                nTCSQLToArr:=TCSQLToArr(cSXBTableQuery,@aTCSQLToArr,nil,aTCSQLSetFields,aSXBDBStruct)
                nSXBItens:=Len(aTCSQLToArr)
                for nSXBItem:=1 to nSXBItens
                    if (SXB->(RecLock("SXB",.T.)))
                        for nSXBField:=1 to nSXBFields
                            if (SXB->(aSXBDBStruct[nSXBField][DBS_NAME]=="XB_ALIAS"))
                                SXB->XB_ALIAS:=cBSXBAlias
                            else
                                SXB->(FieldPut(nSXBField,aTCSQLToArr[nSXBItem][nSXBField]))
                            endif
                        next nSXBField
                        SXB->(MsUnLock())
                    endif
                next nSXBItem
                cSXBAliasSeek:=cBSXBAlias
                cSXBAliasSeek+="2"
                cSXBAliasSeek+="01"
                cSXBAliasSeek+="01"
                if (SXB->(!dbSeek(cSXBAliasSeek,.F.)))
                    if (SXB->(RecLock("SXB",.T.)))
                        SXB->XB_ALIAS:=cBSXBAlias
                        SXB->XB_TIPO:="2"
                        SXB->XB_SEQ:="01"
                        SXB->XB_COLUNA:="01"
                        SXB->XB_DESCRI:="Codigo"
                        SXB->XB_DESCSPA:="Codigo"
                        SXB->XB_DESCENG:="Code"
                        SXB->(MsUnLock())
                    endif
                endif
                cSXBAliasSeek:=cBSXBAlias
                cSXBAliasSeek+="6"
                cSXBAliasSeek+="01"
                cSXBAliasSeek+="01"
                if (SXB->(!dbSeek(cSXBAliasSeek,.F.)))
                    SXB->(RecLock("SXB",.T.))
                else
                    SXB->(RecLock("SXB",.F.))
                endif
                SXB->XB_ALIAS:=cBSXBAlias
                SXB->XB_TIPO:="6"
                SXB->XB_SEQ:="01"
                SXB->XB_COLUNA:="01"
                SXB->XB_DESCRI:="Filtro da Consulta"
                SXB->XB_DESCSPA:="Filtro de Consulta"
                SXB->XB_DESCENG:="Look-up Filter"
                SXB->XB_CONTEM:="SM0->M0_CODIGO==MV_PAR01"
                SXB->(MsUnLock())
            endif
            FWFreeArray(@aTCSQLToArr)
            FWFreeArray(@aSXBDBStruct)
            FWFreeArray(@aTCSQLSetFields)
        endif

        aModulos:=Array(0)
        aRetModName:=RetModName(lAllModulos)
        nATModulo:=aScan(aRetModName,{|e|Right(e[2],Len(cModulo))==cModulo})
        aEval(aRetModName,{|e|aAdd(aModulos,e[2]+" : "+e[3])})

        aPBoxPrm:=Array(0)
        //01----------------------------------------------------------------------------------------------
        aAdd(aPBoxPrm,Array(9))
        nPBox:=Len(aPBoxPrm)
        aPBoxPrm[nPBox][1]:=1//[1]:1 - MsGet
        aPBoxPrm[nPBox][2]:="Company"//[2]:Descricao
        aPBoxPrm[nPBox][3]:=cCompany//[3]:String contendo o inicializador do campo
        aPBoxPrm[nPBox][4]:="@!"//[4]:String contendo a Picture do campo
        aPBoxPrm[nPBox][5]:="(UniqueKey(NIL,'SM0',.T.),ExistCpo('SM0',MV_PAR01,1))"//[5]:String contendo a validacao
        aPBoxPrm[nPBox][6]:=cCSXBAlias//[6]:Consulta F3
        aPBoxPrm[nPBox][7]:="(UniqueKey(NIL,'SM0',.T.),AllWaysTrue())"//[7]:String contendo a validacao When
        aPBoxPrm[nPBox][8]:=(CalcFieldSize("C",SM0->(Len(M0_CODIGO)),0,aPBoxPrm[nPBox][4],aPBoxPrm[nPBox][2])+10)//[8]:Tamanho do MsGet
        aPBoxPrm[nPBox][9]:=.T.//[9]:Flag .T./.F. Parametro Obrigatorio ?
        //02----------------------------------------------------------------------------------------------
        aAdd(aPBoxPrm,Array(9))
        nPBox:=Len(aPBoxPrm)
        aPBoxPrm[nPBox][1]:=1//[1]:1 - MsGet
        aPBoxPrm[nPBox][2]:="Branch"//[2]:Descricao
        aPBoxPrm[nPBox][3]:=cBranch//[3]:String contendo o inicializador do campo
        aPBoxPrm[nPBox][4]:="@!"//[4]:String contendo a Picture do campo
        aPBoxPrm[nPBox][5]:="(UniqueKey(NIL,'SM0',.T.),ExistCpo('SM0',MV_PAR01+MV_PAR02,1))"//[5]:String contendo a validacao
        aPBoxPrm[nPBox][6]:=cBSXBAlias//[6]:Consulta F3
        aPBoxPrm[nPBox][7]:="(AllWaysTrue())"//[7]:String contendo a validacao When
        aPBoxPrm[nPBox][8]:=(CalcFieldSize("C",FWSizeFilial(),0,aPBoxPrm[nPBox][4],aPBoxPrm[nPBox][2])+10)//[8]:Tamanho do MsGet
        aPBoxPrm[nPBox][9]:=.T.//[9]:Flag .T./.F. Parametro Obrigatorio ?
        //03----------------------------------------------------------------------------------------------
        aAdd(aPBoxPrm,Array(8))
        nPBox:=Len(aPBoxPrm)
        aPBoxPrm[nPBox][1]:=3//[1]:3 - Radio
        aPBoxPrm[nPBox][2]:="Select the system module"//[2] : Descricao
        aPBoxPrm[nPBox][3]:=nATModulo //[3] : Numerico contendo a opcao inicial do Radio
        aPBoxPrm[nPBox][4]:=aModulos//[4] : Array contendo as opcoes do Radio
        aPBoxPrm[nPBox][5]:=150//[5] : Tamanho do Radio
        aPBoxPrm[nPBox][6]:="AllWaysTrue()"//[6] : Validacao
        aPBoxPrm[nPBox][7]:=.T. //[7] : Flag .T./.F. Parametro Obrigatorio ?
        aPBoxPrm[nPBox][8]:="AllWaysTrue()"//[8] : String contendo a validacao When

        saveInter()
            oParamBoxLoad:=ParamBoxLoad():New(cStack/*cLoad*/,.T./*lCanSave*/,.T./*lUserSave*/)
            MV_PAR01:=oParamBoxLoad:ParamLoad(aPBoxPrm,1,cCompany/*xDefault*/,.F./*lDefault*/)
            MV_PAR02:=oParamBoxLoad:ParamLoad(aPBoxPrm,2,cBranch/*xDefault*/,.F./*lDefault*/)
            bParamBoxOK:={||ExistCpo("SM0",MV_PAR01,1).and.ExistCpo("SM0",MV_PAR01+MV_PAR02,1)}
            lParamBox:=ParamBox(@aPBoxPrm,ProcName(),@aPBoxRet,bParamBoxOK/*bOk*/,/*aButtons*/,.T./*lCentered*/,/*nPosx*/,/*nPosy*/,/*oDlgWizard*/,oParamBoxLoad:GetParamLoad()/*cLoad*/,oParamBoxLoad:GetCanSave()/*lCanSave*/,oParamBoxLoad:GetUserSave()/*lUserSave*/)
            oParamBoxLoad:ParamSave(aPBoxPrm)
            if (lParamBox)
                SM0->(dbSetOrder(1))
                if (SM0->(!dbSeek(MV_PAR01+MV_PAR02,.F.)))
                    lParamBox:=ApMsgYesNo("Empresa ("+MV_PAR01+") e/ou Filial ("+MV_PAR02+") Invalida(s). Deseja selecionar novamente?","ATENCAO")
                    if (lParamBox)
                        if (lParamBox:=ChangeCompanyAndBranch(MV_PAR01,MV_PAR02,.F.))
                            oParamBoxLoad:ParamReLoad(aPBoxPrm,@aPBoxRet,.F.)
                            oParamBoxLoad:ParamSave(aPBoxPrm)
                        endif
                    endif
                else
                    oParamBoxLoad:ParamReLoad(aPBoxPrm,@aPBoxRet,.F.)
                endif
                oParamBoxLoad:ParamSave(aPBoxPrm)
                if (lParamBox)
                    cCompany:=aPBoxRet[1]
                    cBranch:=aPBoxRet[2]
                    nATModulo:=aPBoxRet[3]
                else
                    MV_PAR01:=cEmpAnt
                    MV_PAR02:=cFilAnt
                    MV_PAR02:=nModulo
                    oParamBoxLoad:ParamSave(aPBoxPrm)
                endif
            endif
        restInter()

        FreeObj(@oParamBoxLoad)

        FWFreeArray(@aPBoxPrm)
        FWFreeArray(@aPBoxRet)
        FWFreeArray(@aModulos)
        FWFreeArray(@aRetModName)

        DelClassIntF()

        //Reseta UniqueKey do Filtro SXB
        UniqueKey()

    endif

    if (lParamBox)
        lRPCTools:=FindClass("dna.tech.RPCTools")
        if (lRPCTools)
            if (lIsBlind)
                lChangeOK:=dna.tech.RPCTools():RPCSetEnv(cCompany,cBranch,cEnvServer)
            else
                FWMsgRun(nil,{||lChangeOK:=dna.tech.RPCTools():RPCSetEnv(cCompany,cBranch,cEnvServer)},"Wait...","Changing Company and Branch")
            endif
        else
            if (lIsBlind)
                lChangeOK:=dna.tech.RPCTools():RPCSetEnv(cCompany,cBranch,cEnvServer)
            else
                FWMsgRun(nil,{||lChangeOK:=RPCSetEnv(cCompany,cBranch,cEnvServer)},"Wait...","Changing Company and Branch")
            endif
        endif
        if (!Empty(nATModulo))
            aRetModName:=RetModName(lAllModulos)
            SetModulo(aRetModName[nATModulo][2],Right(aRetModName[nATModulo][2],Len(cModulo)))
            FWFreeArray(@aRetModName)
        endif
    endif

return(lChangeOK)

method SBAdminCheck(cSBAdminPath) class FWExampleTools
return(FWSBAdminTools():SBAdminCheck(@cSBAdminPath))
