/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

    The source code `fw.webex.jsonobject.merge.tlpp` is based on a more detailed and feature-rich
    source code, `dna.tech.jsonobject.merge.tlpp`, and implements part of the functionalities
    present in the latter.

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

#include "totvs.ch"
#include "parmtype.ch"

namespace FWWebEx
using namespace FWWebEx

class JSONObjectMerge from FWWebEx.JSONObjectTools
    static method MergeJSON(jTarget as json,jSource as json) as json
end class

static method MergeJSON(jTarget,jSource) class JSONObjectMerge
return(JSONObjectTools():MergeJSON(jTarget,jSource))
