/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

    The source code `fw.webex.jsonobject.clone.tlpp` is based on a more detailed and feature-rich
    source code, `dna.tech.jsonobject.clone.tlpp`, and implements part of the functionalities
    present in the latter.

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

#include "totvs.ch"
#include "parmtype.ch"

namespace FWWebEx
using namespace FWWebEx

class JSONObjectClone from FWWebEx.JSONObjectTools
    static method CloneJSON(jObject as json) as json
end class

static method CloneJSON(jObject) class JSONObjectClone
return(JSONObjectTools():CloneJSON(jObject))
