/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

namespace FWWebEx

#include "fw.webex.th"

class FWSBAdminTools

    //https://startbootstrap.com/template/sb-admin
    static method SBAdminCheck() as logical

endclass

method SBAdminCheck(cSBAdminPath) class FWSBAdminTools
    local lRet:=.T. as logical
    paramtype cSBAdminPath as character optional
    //TODO: Adicionar como Feature
    cSBAdminPath:="https://cdn.jsdelivr.net/gh/StartBootstrap/startbootstrap-sb-admin@master/dist/"
return(lRet)
