/*
  __                            _
 / _|__      ____      __  ___ | |__    ___ __  __
| |_ \ \ /\ / /\ \ /\ / / / _ \| '_ \  / _ \\ \/ /
|  _| \ V  V /  \ V  V / |  __/| |_) ||  __/ >  <
|_|    \_/\_/    \_/\_/   \___||_.__/  \___|/_/\_\

Released to Public Domain.
--------------------------------------------------------------------------------------
*/

#include "fw.webex.th"

namespace FWWebEx

class WebExFeatureBackURLButton from WebExControl
    protected data oFeature as object
    public method Enable() as object
    public method Load(oControl as object) as object
end class

method Enable() class WebExFeatureBackURLButton
    local oFeature as object
    _Super:New()
    ::oFeature:=self
    oFeature:=::oFeature
    ::AddFeature(oFeature,{|oControl|oFeature:Load(oControl)})
return(self)

method Load(oControl) class WebExFeatureBackURLButton

    paramtype 1 var oControl as object

    //WebExBackURLButton
    WITH WEBEXOBJECT oControl
        //WebExBackURLButton
            WITH WEBEXOBJECT CLASS WebExScript
                .:SetContent(GetWebExBackURLButtonScript())
            END WEBEXOBJECT NOADDCHILD
        //WebExBackURLButton
    END WEBEXOBJECT NOADDCHILD
    //WebExBackURLButton

return(self)
