name: Update Clone Badge

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:       # Também permite rodar manualmente

jobs:
  get-clone-count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3

    - name: Buscar dados de clones da API do GitHub
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -s -H "Authorization: token $GH_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/DNATechByNaldoDJ/fw.webex/traffic/clones \
             -o clones.json

        CLONES=$(jq '.count' clones.json)
        echo "{ \"schemaVersion\": 1, \"label\": \"clones\", \"message\": \"${CLONES}\", \"color\": \"blue\" }" > clone-badge.json

    - name: Commit e push do badge usando GH_TOKEN
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "Automated Badge Bot"
        git config user.email "badgebot@users.noreply.github.com"

        git add clone-badge.json
        git commit -m "Atualiza badge de clones" || echo "Nada para commitar"

        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/DNATechByNaldoDJ/fw.webex.git
        git push origin HEAD:main
